//timestamp recorder for variable tester

var interval = 1;
var curSec = 0;
var duration = 0;
var scoreArr = [[0, "0\'0\"", 0]];    //(time(s), time(m/s), score)
var scoreCorrection;
var resetScore;
function initScoreArray() {
    getDuration();
    for (var i = 1; i <= duration; i++) {
        var tmpMS = (parseInt(i / 60)) + "\'" + (i % 60) + "\"";
        scoreArr.push([i, tmpMS, 0]);
    }
    scoreCorrection = setInterval(scoreCorrect, interval);  //update score to the scoreboard to display
}
    function getDuration() {
        duration = parseInt(vidPlayer.duration) + 1;
    }
    function scoreCorrect() {
        if (score > 5) {
            score = 5;
        }
        else if (score < -5) {
            score = -5;
        }
        //scoreboard.innerHTML = score;
        //scoreboardDisplay();
        scoreRecord();
    }
        function scoreRecord() {
            getCurrentPlayTime();
            scoreArr[curSec][2] = score;
        }
            function getCurrentPlayTime() {
                curSec = parseInt(vidPlayer.currentTime);
            }

function endScoring() {
    //clearInterval(scoringUpdate);
    document.querySelector("#endTest").style.display = "none";
    clearInterval(resetScore);
    clearInterval(scoreCorrection);
    vidPlayer.pause();
    var left = duration - curSec;
    scoreArr.splice(curSec + 1, left);
    chartPreprocess();
    //initChart();
    saveToCSV();
}

var csvFile;
var fullDate;
function saveToCSV() {
    var date = new Date();
    fullDate = date.getFullYear() + "/" + (date.getMonth() + 1) + "/" + date.getDate();
    var directions = "This file is generated by the Variable Tester. \r\n" + "Created on " + fullDate + " for " + subjectName + " with variable " + fullVar + ". \r\n\r\n" + "time(s),time(m/s)," + var1.toLowerCase()  + "\r\n";
    csvFile = "data:text/csv;charset=utf-8," + directions;
    
    scoreArr.forEach(function(rowArray) {
        let row = rowArray.join(",");
        csvFile += row + "\r\n";
    });
    
    var encodedUri = encodeURI(csvFile);
    var link = document.querySelector("#csvDown");
    link.setAttribute("href", encodedUri);
    var fileName = subjectName + " " + var1 + ".csv";
    link.setAttribute("download", fileName);
}